<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Spatial and temporal requirements of breeding Least Terns in the Barataria-Terrebonne National Estuary through the use of Motus automated radio-telemetry data</title>
  <meta name="description" content="Spatial and temporal requirements of breeding Least Terns in the Barataria-Terrebonne National Estuary through the use of Motus automated radio-telemetry data">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Spatial and temporal requirements of breeding Least Terns in the Barataria-Terrebonne National Estuary through the use of Motus automated radio-telemetry data" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Spatial and temporal requirements of breeding Least Terns in the Barataria-Terrebonne National Estuary through the use of Motus automated radio-telemetry data" />
  
  
  

<meta name="author" content="Zoe Crysler, Stuart Mackenzie, Adam Smith">


<meta name="date" content="2020-01-16">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="Methods.html">
<link rel="next" href="Conclusions.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">LETE analysis</a></strong></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="Methods.html"><a href="Methods.html"><i class="fa fa-check"></i><b>1</b> Methods</a><ul>
<li class="chapter" data-level="1.1" data-path="Methods.html"><a href="Methods.html#data-download"><i class="fa fa-check"></i><b>1.1</b> Data Download</a></li>
<li class="chapter" data-level="1.2" data-path="Methods.html"><a href="Methods.html#data-cleaning"><i class="fa fa-check"></i><b>1.2</b> Data Cleaning</a></li>
<li class="chapter" data-level="1.3" data-path="Methods.html"><a href="Methods.html#data-manipulation"><i class="fa fa-check"></i><b>1.3</b> Data Manipulation</a></li>
<li class="chapter" data-level="1.4" data-path="Methods.html"><a href="Methods.html#site-visits"><i class="fa fa-check"></i><b>1.4</b> Site Visits</a></li>
<li class="chapter" data-level="1.5" data-path="Methods.html"><a href="Methods.html#time-partitioning"><i class="fa fa-check"></i><b>1.5</b> Time Partitioning</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Results.html"><a href="Results.html"><i class="fa fa-check"></i><b>2</b> Results</a><ul>
<li class="chapter" data-level="2.1" data-path="Results.html"><a href="Results.html#study-area"><i class="fa fa-check"></i><b>2.1</b> Study Area</a></li>
<li class="chapter" data-level="2.2" data-path="Results.html"><a href="Results.html#detection-overview"><i class="fa fa-check"></i><b>2.2</b> Detection Overview</a></li>
<li class="chapter" data-level="2.3" data-path="Results.html"><a href="Results.html#foraging-vs-incubating"><i class="fa fa-check"></i><b>2.3</b> Foraging vs Incubating</a></li>
<li class="chapter" data-level="2.4" data-path="Results.html"><a href="Results.html#heavily-frequented-foraging-areas"><i class="fa fa-check"></i><b>2.4</b> Heavily Frequented Foraging Areas</a><ul>
<li class="chapter" data-level="2.4.1" data-path="Results.html"><a href="Results.html#simultaneous-detections"><i class="fa fa-check"></i><b>2.4.1</b> Simultaneous Detections</a></li>
<li class="chapter" data-level="2.4.2" data-path="Results.html"><a href="Results.html#detection-directions"><i class="fa fa-check"></i><b>2.4.2</b> Detection Directions</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="Results.html"><a href="Results.html#mean-distances-travelled-for-foraging"><i class="fa fa-check"></i><b>2.5</b> Mean Distances Travelled for Foraging</a></li>
<li class="chapter" data-level="2.6" data-path="Results.html"><a href="Results.html#time-partitioning-between-foraging-and-nest-site-attendance"><i class="fa fa-check"></i><b>2.6</b> Time Partitioning Between Foraging and Nest Site Attendance</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Conclusions.html"><a href="Conclusions.html"><i class="fa fa-check"></i><b>3</b> Conclusions</a><ul>
<li class="chapter" data-level="3.1" data-path="Conclusions.html"><a href="Conclusions.html#heavily-frequented-foraging-areas-1"><i class="fa fa-check"></i><b>3.1</b> Heavily Frequented Foraging Areas</a></li>
<li class="chapter" data-level="3.2" data-path="Conclusions.html"><a href="Conclusions.html#mean-distances-travelled-for-foraging-1"><i class="fa fa-check"></i><b>3.2</b> Mean Distances Travelled for Foraging</a></li>
<li class="chapter" data-level="3.3" data-path="Conclusions.html"><a href="Conclusions.html#time-partitioning-between-foraging-and-nest-site-attendance-1"><i class="fa fa-check"></i><b>3.3</b> Time Partitioning Between Foraging and Nest Site Attendance</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="Recommendations.html"><a href="Recommendations.html"><i class="fa fa-check"></i><b>4</b> Recommendations</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="AppendixA.html"><a href="AppendixA.html"><i class="fa fa-check"></i><b>A</b> Appendix A - Downloading and Cleaning Data</a><ul>
<li class="chapter" data-level="A.1" data-path="AppendixA.html"><a href="AppendixA.html#loading-packages"><i class="fa fa-check"></i><b>A.1</b> Loading Packages</a></li>
<li class="chapter" data-level="A.2" data-path="AppendixA.html"><a href="AppendixA.html#data-download---project-132"><i class="fa fa-check"></i><b>A.2</b> Data Download - project 132</a></li>
<li class="chapter" data-level="A.3" data-path="AppendixA.html"><a href="AppendixA.html#accessing-data"><i class="fa fa-check"></i><b>A.3</b> Accessing Data</a></li>
<li class="chapter" data-level="A.4" data-path="AppendixA.html"><a href="AppendixA.html#dataframe-of-motustagid-and-lotek-tag-id"><i class="fa fa-check"></i><b>A.4</b> Dataframe of motusTagID and Lotek tag ID</a></li>
<li class="chapter" data-level="A.5" data-path="AppendixA.html"><a href="AppendixA.html#cleaning-data"><i class="fa fa-check"></i><b>A.5</b> Cleaning Data</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="AppendixB.html"><a href="AppendixB.html"><i class="fa fa-check"></i><b>B</b> Appendix B - Distances Between Receivers</a></li>
<li class="chapter" data-level="C" data-path="AppendixC.html"><a href="AppendixC.html"><i class="fa fa-check"></i><b>C</b> Appendix C - Site Visits</a><ul>
<li class="chapter" data-level="C.1" data-path="AppendixC.html"><a href="AppendixC.html#unique-visits"><i class="fa fa-check"></i><b>C.1</b> Unique Visits</a></li>
<li class="chapter" data-level="C.2" data-path="AppendixC.html"><a href="AppendixC.html#visits-by-tag-and-station"><i class="fa fa-check"></i><b>C.2</b> Visits by tag and station</a></li>
<li class="chapter" data-level="C.3" data-path="AppendixC.html"><a href="AppendixC.html#visits-by-station"><i class="fa fa-check"></i><b>C.3</b> Visits by Station</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Spatial and temporal requirements of breeding Least Terns in the Barataria-Terrebonne National Estuary through the use of Motus automated radio-telemetry data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="Results" class="section level1">
<h1><span class="header-section-number">2</span> Results</h1>
<div id="study-area" class="section level2">
<h2><span class="header-section-number">2.1</span> Study Area</h2>
<p>Stations within the study region are presented in Figure <a href="Results.html#fig:2017StationMap">2.1</a>, stations with red outlines had no detections, while coloured stations had at least one tag detected during the study period from 2017 to 2018. Triangles represent receivers that were active during 2017 <em>and</em> 2018, circles represent stations that were only active in 2017 (<em>Quintana</em> and <em>East Grand Terre</em>). The blue lines indicate the direction of antennas during the study period and span 15 miles from the receiver. All receivers maintained the same bearings throughout the study period with the exception of <em>Bolivar_Flats</em>, here the solid blue lines are the 2017 bearings, while the dashed blue lines are the 2018 bearings.</p>
<p>All Least Terns were tagged within close proximity of <em>Exxon Fields</em>, and for the purposes of this report stations considered within proximity to the breeding area are <em>Exxon Fields</em>, <em>East Grand Terre</em>, <em>Grand_Isle</em>, and <em>Wisner.</em> A close up of this area is presented in the inset of Figure <a href="Results.html#fig:2017StationMap">2.1</a>.</p>
<div class="figure"><span id="fig:2017StationMap"></span>
<img src="LETE_Analysis_files/figure-html/2017StationMap-1.png" alt="Map of study region during 2017 and 2018. Triangles represent receivers that were active during 2017 and 2018, circles represent stations that were only active in 2017. Stations outlined in a red circle had no detections while coloured stations had at least one detection during the study period. Blue lines indicate antenna bearings spanning 15 miles from the station, bearings remained constant throughout the study period with the exception of *Bolivar_Flats* where the solid lines indicate 2017 bearings and dashed lines indicate 2018 bearings." width="672" />
<p class="caption">
Figure 2.1: Map of study region during 2017 and 2018. Triangles represent receivers that were active during 2017 and 2018, circles represent stations that were only active in 2017. Stations outlined in a red circle had no detections while coloured stations had at least one detection during the study period. Blue lines indicate antenna bearings spanning 15 miles from the station, bearings remained constant throughout the study period with the exception of <em>Bolivar_Flats</em> where the solid lines indicate 2017 bearings and dashed lines indicate 2018 bearings.
</p>
</div>
</div>
<div id="detection-overview" class="section level2">
<h2><span class="header-section-number">2.2</span> Detection Overview</h2>
<p>In 2017, only one individual (tag ID 136) was detected at stations outside the immediate tagging region, all other individuals and the bulk of the detections occurred at <em>Exxon Fields</em>, <em>East Grand Terre</em>, <em>Grand_Isle</em>, and <em>Wisner.</em> Figure <a href="Results.html#fig:2017DetectionMap">2.2</a> shows a map of all 2017 tagged bird detections, lines are coloured by tag ID. Figure <a href="Results.html#fig:2017LongitudePlots">2.3</a> displays the same data by plotting latitude vs. time for each tag, with points coloured by receiver site.</p>
<div class="figure"><span id="fig:2017DetectionMap"></span>
<img src="LETE_Analysis_files/figure-html/2017DetectionMap-1.png" alt="Map of 2017 tag detections, only tag 136 was detected outside the immediate tagging region." width="672" />
<p class="caption">
Figure 2.2: Map of 2017 tag detections, only tag 136 was detected outside the immediate tagging region.
</p>
</div>
<div class="figure"><span id="fig:2017LongitudePlots"></span>
<img src="LETE_Analysis_files/figure-html/2017LongitudePlots-1.png" alt="Individual 2017 plots by Motus tag ID showing latitudinal movements of tags over time, detection points are coloured by station location. Note that the x and y scales vary between tag plots." width="672" />
<p class="caption">
Figure 2.3: Individual 2017 plots by Motus tag ID showing latitudinal movements of tags over time, detection points are coloured by station location. Note that the x and y scales vary between tag plots.
</p>
</div>
<p>In 2018, again only one individual was detected outside the immediate tagging region (tag ID 283), all other individuals and the bulk of the detections occurred at <em>Exxon Fields</em>, <em>East Grand Terre</em>, and <em>Grand_Isle</em>. Note that in 2018 no birds were detected at <em>Wisner</em> despite close proximity to nesting areas. Based on receiver performance outputs, this is likely due to receiver functionality rather than a true lack of detections. Figure <a href="Results.html#fig:2018DetectionMap">2.4</a> shows a map of detection pattern of all 2018 tagged birds, while Figure <a href="Results.html#fig:2018LongitudePlots">2.5</a> displays the same data as individual tag plots of latitude vs. time.</p>
<div class="figure"><span id="fig:2018DetectionMap"></span>
<img src="LETE_Analysis_files/figure-html/2018DetectionMap-1.png" alt="Map of 2018 tag detections, only tag 283 was detected outside the immediate tagging region." width="672" />
<p class="caption">
Figure 2.4: Map of 2018 tag detections, only tag 283 was detected outside the immediate tagging region.
</p>
</div>
<div class="figure"><span id="fig:2018LongitudePlots"></span>
<img src="LETE_Analysis_files/figure-html/2018LongitudePlots-1.png" alt="Individual 2018 plots by tag ID showing latitudinal movements of tags over time, detection points are coloured by station location. Note that the x and y scales vary between tag plots." width="672" />
<p class="caption">
Figure 2.5: Individual 2018 plots by tag ID showing latitudinal movements of tags over time, detection points are coloured by station location. Note that the x and y scales vary between tag plots.
</p>
</div>
</div>
<div id="foraging-vs-incubating" class="section level2">
<h2><span class="header-section-number">2.3</span> Foraging vs Incubating</h2>
<div class="figure"><span id="fig:incubatingBirds"></span>
<img src="LETE_Analysis_files/figure-html/incubatingBirds-1.png" alt="Signal strength vs. time of four representative tags at select periods of incubation. Points represent individual detections coloured by Receiver, vertical blue lines indicate dusk, and vertical orange lines indicate dawn. A higher signal strength correlates to a stronger detection. Note x and y scales vary between plots." width="672" />
<p class="caption">
Figure 2.6: Signal strength vs. time of four representative tags at select periods of incubation. Points represent individual detections coloured by Receiver, vertical blue lines indicate dusk, and vertical orange lines indicate dawn. A higher signal strength correlates to a stronger detection. Note x and y scales vary between plots.
</p>
</div>
<p>Figure <a href="Results.html#fig:incubatingBirds">2.6</a> is a selection of 4 representative detection patterns of individuals; examining the signal strength it is not always clear when birds are attending the nest site and when they are foraging. For example, tag 94 shows clear daily signal strength patterns, with low signal strength occurring overnight when the bird is likely incubating. Tag 93 has a similar but less distinct pattern; some nights the bird is detected while other nights it is not. In other cases the tag is picked up far less consistently as in tag 303, and in even more extreme cases as in tag 289. For these final two tags, the bird is rarely if ever detected while incubating, and most detections likely occur as the bird is leaving or arriving at the nest site.</p>
<p>Furthermore, even in tags with clear daily detection patterns as in tag 94, shorter nest site attendance periods during the day are not as obviously picked up. However, based on these detections, the signal strength during incubation is generally much lower than during flight. This is to be expected as a tags detection range increases substantially when a bird is in the air as compared to on the ground (low signal strength = weaker detection). Therefore, all detections on the <em>Exxon Fields</em> receiver with a signal strength &lt; 70 will be excluded from foraging analysis from this point forward to exclude likely detections on the nest during incubation. While this will invariably also remove detections on <em>Exxon Fields</em> that may occur when the bird is in flight, since the station is in very close proximity to the nesting site, in most cases this will only remove the tail ends of a detection streak as the bird is departing or approaching the nesting site.</p>
</div>
<div id="heavily-frequented-foraging-areas" class="section level2">
<h2><span class="header-section-number">2.4</span> Heavily Frequented Foraging Areas</h2>
<p>To add meaning to receiver detections, the distance from <em>Exxon Fields</em> was calculated for each station where tags were detected and are presented in <a href="Results.html#tab:distanceTable">table 2.1</a>. A full database with distances calculated between all stations can be found in <a href="AppendixB.html#AppendixB">Appendix B</a>.</p>
<table style="width:85%;">
<caption><span id="tab:distanceTable">Table 2.1: </span> Distance in miles between each receiver and Exxon Fields</caption>
<colgroup>
<col width="44%" />
<col width="40%" />
</colgroup>
<thead>
<tr class="header">
<th>Site Name</th>
<th>Distance from Exxon Fields (mi)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>Exxon Fields</p></td>
<td><p>0</p></td>
</tr>
<tr class="even">
<td><p>Grand_Isle</p></td>
<td><p>1.967</p></td>
</tr>
<tr class="odd">
<td><p>East Grand Terre</p></td>
<td><p>7.848</p></td>
</tr>
<tr class="even">
<td><p>Wisner</p></td>
<td><p>14.34</p></td>
</tr>
<tr class="odd">
<td><p>Rock W</p></td>
<td><p>175</p></td>
</tr>
<tr class="even">
<td><p>Sabine NWR</p></td>
<td><p>211.1</p></td>
</tr>
<tr class="odd">
<td><p>High_Island</p></td>
<td><p>267.2</p></td>
</tr>
<tr class="even">
<td><p>Bolivar_Flats</p></td>
<td><p>288.4</p></td>
</tr>
<tr class="odd">
<td><p>Scenic Galveston</p></td>
<td><p>298.4</p></td>
</tr>
<tr class="even">
<td><p>Brazoria National Wildlife Refuge</p></td>
<td><p>320.9</p></td>
</tr>
<tr class="odd">
<td><p>Quintana</p></td>
<td><p>323.5</p></td>
</tr>
<tr class="even">
<td><p>San Bernard National Wildlife Refuge Headquarters</p></td>
<td><p>339.8</p></td>
</tr>
<tr class="odd">
<td><p>San Bernard NWR (Big Pond Unit)</p></td>
<td><p>353.6</p></td>
</tr>
<tr class="even">
<td><p>Rockport Bay Education Center</p></td>
<td><p>437.9</p></td>
</tr>
</tbody>
</table>
<p>For each station the total number of visits was calculated (Figure <a href="Results.html#fig:visitFrequency">2.7</a>), as expected <em>Exxon Fields</em> had by far the highest number of visits as it was at the nesting area. In 2017 and 2018 <em>Grand_Isle</em> had the next highest frequency of detections, this is not surprising as it is the closest station to the nesting area (see <a href="Results.html#tab:distanceTable">table 2.1</a>). <em>East Grand Terre</em> and <em>Wisner</em> followed with lower numbers of site visits and are also near the nesting area. Note the lack of detections at <em>Wisner</em> in 2018, this is likely due to receiver malfunction rather than a true lack of detections. All other stations had negligible (&lt;3) visits and are substantially farther away from the nesting grounds.</p>
<div class="figure"><span id="fig:visitFrequency"></span>
<img src="LETE_Analysis_files/figure-html/visitFrequency-1.png" alt="Detection frequencies of tags at each station by year, ordered by distance from *Exxon Fields*" width="672" />
<p class="caption">
Figure 2.7: Detection frequencies of tags at each station by year, ordered by distance from <em>Exxon Fields</em>
</p>
</div>
<p>The length of visits was consistent with the number of visits, that is, birds generally had longer detection periods at <em>Exxon Fields</em>, followed by <em>East Grand Terre</em>, <em>Grand_Isle</em>, and <em>Wisner</em>. However, for both 2017 and 2018 only <em>Grand_Isle</em> and <em>Exxon Fields</em> differed significantly (p &lt; 0.001) in their visit length. Figure <a href="Results.html#fig:visitLength">2.8</a> shows the mean length of time each bird was detected at each station during each visit (See <a href="AppendixC.html#AppendixC">Appendix C</a> for complete visit information).</p>
<div class="figure"><span id="fig:visitLength"></span>
<img src="LETE_Analysis_files/figure-html/visitLength-1.png" alt="Mean length of foraging visits in minutes at each station for 2017 and 2018, ordered by distance from Exxon Fields. Note that the plot has been cut off due to the high number of outliers, *Exxon Fields* had a maximum visit length of 61 minutes, *Grand_Isle* 107 minutes, *East Grand Terre* 19 minutes, *Wisner* 27 minutes." width="672" />
<p class="caption">
Figure 2.8: Mean length of foraging visits in minutes at each station for 2017 and 2018, ordered by distance from Exxon Fields. Note that the plot has been cut off due to the high number of outliers, <em>Exxon Fields</em> had a maximum visit length of 61 minutes, <em>Grand_Isle</em> 107 minutes, <em>East Grand Terre</em> 19 minutes, <em>Wisner</em> 27 minutes.
</p>
</div>
<p>Of the birds that were detected at <em>Exxon Fields</em> in 2017 and 2018, all were detected on at least 6 different visits. At <em>Grand_Isle</em>, the majority (39/44, 88.6%) of birds were detected on more than 2 separate occasions (&gt;2 discrete visits). In comparison, at the remaining stations less than half (10/23, 43.5%) were detected on more than two occasions. Only tag 141 appeared semi-regularly at <em>Wisner</em> but is notable in 12 detections.</p>
<p>Thus birds appear to spend the majority of their time in close proximity to <em>Exxon Fields</em>, however this could be a by-product of increased detection due to proximity to nesting sites and therefore a necessity to frequently pass the receiver regardless of whether foraging is occurring nearby or not. Most birds frequented <em>Grand_Isle</em> regularly which could be due to nearby foraging, or a proximity to the nesting site.</p>
<div id="simultaneous-detections" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Simultaneous Detections</h3>
<p>If stations are within close proximity of one another, it’s possible to get simultaneous detections on both stations at once. During incubation there were 208 pairs of simultaneous detections, 2 of these occurred between <em>East Grand Terre</em> and <em>Exxon Fields</em>, 3 between <em>East Grand Terre</em> and <em>Grand_Isle</em>, and the other 203 between <em>Exxon Fields</em> and <em>Grand_Isle</em>. <em>Exxon Fields</em> and <em>Grand_Isle</em> are the closest two stations at 1.97 miles apart, easily within range of each other particularly when birds are in flight (see <a href="AppendixB.html#AppendixB">Appendix B</a>). <em>East Grand Terre</em> is 7.85 miles and 9.80 miles away from <em>Exxon Fields</em> and <em>Grand_Isle</em> respectively, the next closest pairs of stations.</p>
</div>
<div id="detection-directions" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Detection Directions</h3>
<p>We can narrow down the areas visited beyond which site they were detected at by examining which antenna they were detected on during foraging. Figures <a href="Results.html#fig:detBearings2017">2.9</a> and <a href="Results.html#fig:detBearings2018">2.10</a> show the total number of detections for each antenna bearing at each site for 2017 and 2018 respectively, while figures <a href="Results.html#fig:CumulativeDetectionTimeMap17">2.11</a> and <a href="Results.html#fig:CumulativeDetectionTimeMap18">2.12</a> show the total number of birds and cumulative detection time of each antenna at each site for 2017 and 2018 respectively.</p>
<div class="figure"><span id="fig:detBearings2017"></span>
<img src="LETE_Analysis_files/figure-html/detBearings2017-1.png" alt="Frequency of all 2017 foraging detections on each antenna. Increasingly darker blue bars indicate increased numbers of detections during the incubation period, orange lines indicate antenna bearings at each site. Note that scales differ by site." width="672" />
<p class="caption">
Figure 2.9: Frequency of all 2017 foraging detections on each antenna. Increasingly darker blue bars indicate increased numbers of detections during the incubation period, orange lines indicate antenna bearings at each site. Note that scales differ by site.
</p>
</div>
<div class="figure"><span id="fig:detBearings2018"></span>
<img src="LETE_Analysis_files/figure-html/detBearings2018-1.png" alt="Frequency of all 2018 foraging detections on each antenna. Increasingly darker blue bars indicate increased numbers of detections during the incubation period, orange lines indicate antenna bearings at each site. Note that scales differ by site." width="672" />
<p class="caption">
Figure 2.10: Frequency of all 2018 foraging detections on each antenna. Increasingly darker blue bars indicate increased numbers of detections during the incubation period, orange lines indicate antenna bearings at each site. Note that scales differ by site.
</p>
</div>
<p>Detection patterns are similar at <em>Exxon Fields</em>, <em>Grand_Isle</em>, and <em>East Grand Terre</em> in 2017 and 2018. Detections at <em>Exxon Fields</em> were predominantly to the SW, directly in line with the tagging area, this also indicates that birds likely arrive and depart to/from the nesting location from the SW. <em>Grand_Isle</em> detections were overwhelmingly more prevalent to the NE, pointing towards the nearby colony, while this may indicate that birds don’t spend much time foraging to the SW, it could also be due to the sheer proximity of the nesting site. As discussed earlier, nearly all cases of simultaneous detections between two stations occur between <em>Exxon Fields</em> and <em>Grand Isle</em>, suggesting that many of the arrival and departure flights from the colony could be captured by both stations, resulting in the high number of NE detections at Grand Isle being an artifact of colony attendance. <em>East Grand Terre</em> had the most detections by far to the SW, again towards the colony.</p>
<p>Both the number of detections and the cumulative detection time was highest at <em>Exxon Fields</em> in both years, followed by <em>Grand_Isle</em> and then <em>East Grand Terre</em>. All 21 individuals with foraging detections in 2017 were detected by both <em>Exxon Fields</em> and <em>Grand_Isle</em>, while in 2018 all 24 foraging individuals were detected at <em>Exxon Fields</em>, only 23 were detected at <em>Grand_Isle</em>. The cumulative detection time at <em>Grand_Isle</em> is also markedly shorter than at <em>Exxon Fiends</em> in 2018. In both years, smaller numbers of birds and shorter cumulative detection times occurred at <em>East Grand Terre</em>, and even fewer at <em>Wisner</em> (as noted previously, a lack of 2018 detections at <em>Wisner</em> is likely due to receiver malfunction rather than true lack of tags in the area).</p>
<p>In 2017, birds were picked up in very small numbers outside of the immediate breeding area. It is difficult to make generalized assumptions from such a small number of detections, however it does seem as though a few birds may be using the areas off the coast around <em>Quintana</em>. There are even fewer detections away from the colony during incubation in 2018, but those that do occur are in the same region.</p>
<div class="figure"><span id="fig:CumulativeDetectionTimeMap17"></span>
<img src="LETE_Analysis_files/figure-html/CumulativeDetectionTimeMap17-1.png" alt="Cumulative 2017 detections of 21 foraging birds by each antenna at the colony site. Solid Blue lines indicate antenna bearings extending outward 10km from the receiver, numbers associated with each antenna indicate the number of tags detected, and the circles surrounding each number are coloured by cumulative detection time." width="480" />
<p class="caption">
Figure 2.11: Cumulative 2017 detections of 21 foraging birds by each antenna at the colony site. Solid Blue lines indicate antenna bearings extending outward 10km from the receiver, numbers associated with each antenna indicate the number of tags detected, and the circles surrounding each number are coloured by cumulative detection time.
</p>
</div>
<div class="figure"><span id="fig:CumulativeDetectionTimeMap18"></span>
<img src="LETE_Analysis_files/figure-html/CumulativeDetectionTimeMap18-1.png" alt="Cumulative 2018 detections of 24 foraging birds by each antenna at the colony site. Solid Blue lines indicate antenna bearings extending outward 10km from the receiver, numbers associated with each antenna indicate the number of tags detected, and the circles surrounding each number are coloured by cumulative detection time." width="480" />
<p class="caption">
Figure 2.12: Cumulative 2018 detections of 24 foraging birds by each antenna at the colony site. Solid Blue lines indicate antenna bearings extending outward 10km from the receiver, numbers associated with each antenna indicate the number of tags detected, and the circles surrounding each number are coloured by cumulative detection time.
</p>
</div>
</div>
</div>
<div id="mean-distances-travelled-for-foraging" class="section level2">
<h2><span class="header-section-number">2.5</span> Mean Distances Travelled for Foraging</h2>
<p>Based on detection data, in 2017 the mean distance travelled for all detection periods was 1.47 miles (SE = 0.38), with a maximum distance travelled to <em>San Bernard NWR (Big Pond Unit)</em> at 353.62 miles. In 2018 the mean distance travelled was 0.50 miles (SE = 0.12), with a maximum distance travelled of 288.39 miles to <em>Bolivar Flats</em>. However, the vast majority of detections (4,670/4,678 or 99.8%) during foraging trips occurred within 14.34 miles from the colony detected at the four closest receiver stations (<em>Exxon Fields</em>, <em>Grand_Isle</em>, <em>East Grand Terre</em>, and <em>Wisner</em>).</p>
</div>
<div id="time-partitioning-between-foraging-and-nest-site-attendance" class="section level2">
<h2><span class="header-section-number">2.6</span> Time Partitioning Between Foraging and Nest Site Attendance</h2>
<p>Only tags detected reliably during incubation at <em>Exxon Fields</em> were used for the following analysis, this included 5 tags from 2017, and 7 tags from 2018. In addition, only detections at <em>Exxon Fields</em> are used in this section.</p>
<div class="figure"><span id="fig:partitionFig17"></span>
<img src="LETE_Analysis_files/figure-html/partitionFig17-1.png" alt="Signal strength vs. time of 2017 tag detections during incubation at nesting site (Exxon Fields), each plot is one individual, red points are detections during the day, and blue points are detections during the night. Orange and blue vertical lines indicate dawn and dusk respectively." width="672" />
<p class="caption">
Figure 2.13: Signal strength vs. time of 2017 tag detections during incubation at nesting site (Exxon Fields), each plot is one individual, red points are detections during the day, and blue points are detections during the night. Orange and blue vertical lines indicate dawn and dusk respectively.
</p>
</div>
<pre><code>## Saving 7 x 7 in image</code></pre>
<div class="figure"><span id="fig:partitionFig18"></span>
<img src="LETE_Analysis_files/figure-html/partitionFig18-1.png" alt="Signal strength vs. time of 2018 tag detections during incubation at nesting site (Exxon Fields), each plot is one individual, red points are detections during the day, and blue points are detections during the night. Orange and blue vertical lines indicate dawn and dusk respectively." width="672" />
<p class="caption">
Figure 2.14: Signal strength vs. time of 2018 tag detections during incubation at nesting site (Exxon Fields), each plot is one individual, red points are detections during the day, and blue points are detections during the night. Orange and blue vertical lines indicate dawn and dusk respectively.
</p>
</div>
<pre><code>## Saving 7 x 7 in image</code></pre>
<p>Colony site (<em>Exxon Fields</em>) detection plots in figures <a href="Results.html#fig:partitionFig17">2.13</a> and <a href="Results.html#fig:partitionFig18">2.14</a> show a clear difference between nocturnal and diurnal behaviours reflected in detection patterns. Nocturnal site visits were on average 30.41 (SE = 4.33) and 16.83 (SE = 1.88) minutes for 2017 and 2018 respectively, while detections during the day were 12.85 (SE = 0.81) and 10.73 (SE = 0.57) minutes for 2017 and 2018 respectively, mean detection length was significantly different (p &lt; 0.001) for both years (<a href="Results.html#tab:partitioningSummary">table 2.2</a>). Signal strength was also significantly different (p &lt; 0.001) between nocturnal and diurnal detections in both years. Mean signal strength for each visit was 65.62 (SE = 1.12) and 59.01 (SE = 1.17) during the night compared 89.84 (SE = 0.73) and 73.58 (SE = 0.84) during the day for 2017 and 2018 respectively. This indicates important daily differences in Least Tern behaviour, during the night birds are more likely to be on the nest resulting in prolonged periods of detections with low signal strength, however during the day as the birds are travelling to and from the nest while foraging, they have shorter periods of nest attendance and higher signal strengths as birds in the air are more readily detected.</p>
<table style="width:88%;">
<caption><span id="tab:partitioningSummary">Table 2.2: </span> Mean length and signal strength of visits during 2017 and 2018 split by day vs. night detections (continued below)</caption>
<colgroup>
<col width="9%" />
<col width="12%" />
<col width="37%" />
<col width="27%" />
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Period</th>
<th>Mean length of detection periods (mins)</th>
<th>Standard error of detection periods</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>2017</p></td>
<td><p>day</p></td>
<td><p>12.85</p></td>
<td><p>0.81</p></td>
</tr>
<tr class="even">
<td><p>2017</p></td>
<td><p>night</p></td>
<td><p>30.41</p></td>
<td><p>4.33</p></td>
</tr>
<tr class="odd">
<td><p>2018</p></td>
<td><p>day</p></td>
<td><p>10.73</p></td>
<td><p>0.57</p></td>
</tr>
<tr class="even">
<td><p>2018</p></td>
<td><p>night</p></td>
<td><p>16.83</p></td>
<td><p>1.88</p></td>
</tr>
</tbody>
</table>
<table style="width:72%;">
<colgroup>
<col width="36%" />
<col width="36%" />
</colgroup>
<thead>
<tr class="header">
<th>Mean signal strength of detections</th>
<th>Standard error signal strength</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>89.84</p></td>
<td><p>0.73</p></td>
</tr>
<tr class="even">
<td><p>65.62</p></td>
<td><p>1.12</p></td>
</tr>
<tr class="odd">
<td><p>73.58</p></td>
<td><p>0.84</p></td>
</tr>
<tr class="even">
<td><p>59.01</p></td>
<td><p>1.17</p></td>
</tr>
</tbody>
</table>
<p>During daylight hours (between dawn and dusk) when Least Terns are actively foraging, they were detected by <em>Exxon Fields</em> on average 22.22% and 16.19% of the time in 2017 and 2018 respectively. As these tags were already screened as tags that are reliably detected during nest attendance, this suggests that during the day the majority of the birds time is spent away from the nest.</p>
<p>By filtering detections even further, and only examining visits that were below the signal strength threshold of 70 with at least 3 detections, we can discern <em>nest</em> attendance. Least Terns had a mean visit length of 13.88 (SE = 1.28) and 13.42 (SE = 0.75) minutes, and on average had 6.7 (SE = 0.79) and 7.3 (SE = 0.62) daily visits to the nest during daylight hours in 2017 and 2018 respectively. Note that this should be treated as anecdotal information due to the small sample size.</p>
<table style="width:85%;">
<caption><span id="tab:nestAttendance">Table 2.3: </span> Mean length and number of daylight nest attendance (signal strength &lt; 70 for visits with at least 3 detections) during 2017 and 2018 (continued below)</caption>
<colgroup>
<col width="9%" />
<col width="37%" />
<col width="37%" />
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Mean length of detection periods (mins)</th>
<th>Standard error detection periods</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>2017</p></td>
<td><p>13.88</p></td>
<td><p>1.28</p></td>
</tr>
<tr class="even">
<td><p>2018</p></td>
<td><p>13.43</p></td>
<td><p>0.75</p></td>
</tr>
</tbody>
</table>
<table style="width:69%;">
<colgroup>
<col width="31%" />
<col width="37%" />
</colgroup>
<thead>
<tr class="header">
<th>Mean number of daily visits</th>
<th>Standard error number of daily visits</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>6.71</p></td>
<td><p>0.79</p></td>
</tr>
<tr class="even">
<td><p>7.333</p></td>
<td><p>0.62</p></td>
</tr>
</tbody>
</table>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="Methods.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="Conclusions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["LETE_Analysis.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
